name: Upload WHL & Run Databricks Job

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_HTTP_PATH: ${{ secrets.DATABRICKS_HTTP_PATH }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          poetry install
          
      - name: Validate Databricks secrets
        run: |
          echo "🔍 Validating Databricks secrets..."

          if [ -z "${DATABRICKS_HOST}" ]; then
            echo "❌ DATABRICKS_HOST is not set"; exit 1;
          fi
          if [ -z "${DATABRICKS_TOKEN}" ]; then
            echo "❌ DATABRICKS_TOKEN is not set"; exit 1;
          fi
          if [ -z "${DATABRICKS_HTTP_PATH}" ]; then
            echo "❌ DATABRICKS_HTTP_PATH is not set"; exit 1;
          fi

          echo "✅ All Databricks secrets found"

      - name: Install Databricks CLI
        run: |
          pip install databricks-cli

      - name: Deploy Databricks Job
        env:
            DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
            DATABRICKS_HTTP_PATH: ${{ secrets.DATABRICKS_HTTP_PATH }}
            DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          pip install databricks-sdk
          python deploy_job.py
        

      - name: Trigger Databricks Job
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: python trigger_job.py
        