name: Deploy Databricks Bundle

# Trigger on every push (commit) to any branch or specific branches
on:
  push:
    # To deploy on all branches:
    branches:
      - '**'
    # Or to deploy only on main or master:
    # branches:
    #   - main
    #   - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
    
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev libffi-dev

      - name: Install databricks-bundle CLI
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools wheel

          # Install PyYAML early to avoid Cython-related build errors in isolation
          pip install "PyYAML<6.0" --no-build-isolation --no-binary :all:

          # Now install databricks-bundle without isolated build
          pip install databricks-bundle --no-build-isolation

      - name: Configure Databricks CLI
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks configure --token <<< "$DATABRICKS_HOST\n$DATABRICKS_TOKEN"

      - name: Validate bundle
        run: databricks-bundle validate

      - name: Deploy bundle
        run: databricks-bundle deploy
